repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--exclude", "docs"]
  - repo: https://github.com/pdm-project/pdm
    rev: 2.4.5
    hooks:
      - id: pdm-lock-check