# NOTE: Need better dynamic versioning before enabling
name: CD

on: workflow_dispatch
  # workflow_run:
  #   workflows: [CI]
  #   types: [completed]
  #   branches:
  #     - main
  #     - develop
  #     - release/*
  #     - hotfix/*

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
          echo 'The triggering workflow passed'
          echo "${{ github.event.workflow_run. }}"
      - name: 'Download artifact'
        uses: actions/github-script@v6
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
