name:  CI/CD

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]


jobs:
  change-matrix:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    permissions:
      pull-requests: read
    steps:
    # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # Use context to get the branch where commits were pushed.
          # If there is only one long-lived branch (e.g. master),
          # you can specify it directly.
          # If it's not configured, the repository default branch is used.
          base: ${{ github.ref }}
          filters: |
            sx-math:
              - "sx-math/**"
              - ".github/workflows/ci*.yaml"
              - ".github/workflows/python*.yaml"
            sx-check:
              - "sx-check/**"
              - ".github/workflows/ci*.yaml"
              - ".github/workflows/python*.yaml"
  python-package:
    name: "${{ matrix.package }}"
    needs: change-matrix
    if: ${{ needs.change-matrix.outputs.packages != '[]' && needs.change-matrix.outputs.packages != '' }}
    strategy:
      fail-fast: false
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        package: ${{ fromJSON(needs.change-matrix.outputs.packages) }}
    uses: ./.github/workflows/python-build.yaml
    with:
      package: ${{ matrix.package }}

