name: PyPI Publish

on:
  workflow_call:
    inputs:
      package:
        description: 'The target project'
        required: true
        type: string
      version:
        description: 'The project version'
        type: string
        default: ''
      pypi_url:
        description: 'PyPI URL'
        type: string
        default: https://test.pypi.org/legacy/
    secrets:
      PYPI_API_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      target:
        description: 'The target project'
        required: true
        type: string
      version:
        description: 'The project version'
        required: true
        type: string
      pypi_url:
        description: 'PyPI URL'
        required: true
        type: string
        default: https://test.pypi.org/legacy/

jobs:
  python-publish:
    name: "Publish ${{ inputs.package }} ${{ inputs.version }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.package }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m pip install build hatch --user
    - name: Check version
      if: inputs.version != ''
      run: >-
        [[ $(hatch version) == ${{ inputs.version }} ]] && echo "version matches" || exit 1
    - name: Build wheel and sdist
      run: >-
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.7
      with:
        password: ${{secrets.PYPI_API_TOKEN}}
        repository-url: ${{ inputs.pypi_url }}
        packages-dir: ${{ inputs.package }}/dist
        skip-existing: true
        print-hash: true
