on:
  push:
    tags:
      - 'sx-*'

jobs:
  parse-tag:
    name: "Parse ${{ github.ref_name }}"
    outputs:
      package: ${{ steps.parse.outputs.PKG }}
      version: ${{ steps.parse.outputs.VER }}
    runs-on: ubuntu-latest
    steps:
      - name: "Parse package and version"
        id: parse
        run: |
          echo "PKG=$(echo ${{ github.ref_name }} | sed -e 's/-[0-9].*//')" >> "$GITHUB_OUTPUT"
          echo "VER=$(echo ${{ github.ref_name }} | sed -e 's/[a-z\-]*-//')" >> "$GITHUB_OUTPUT"
  publish:
    name: "${{ needs.parse-tag.outputs.package }} ${{ needs.parse-tag.outputs.version }}"
    needs: parse-tag
    uses: ./.github/workflows/python-publish.yaml
    with:
      package: ${{ needs.parse-tag.outputs.package }}
      version: ${{ needs.parse-tag.outputs.version }}
    secrets:
      PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}

